export const addProductFormElements = [
  {
    label: "Product Name",
    name: "productName",
    componentType: "input",
    type: "text",
    placeholder: "Enter product name",
  },
  {
    label: "Description",
    name: "description",
    componentType: "textarea",
    placeholder: "Enter product description",
  },
  {
    label: "Product Type",
    name: "productType",
    componentType: "select",
    options: [
      { id: "wallpapers", label: "Wallpapers" },
      { id: "wallpaperRolls", label: "Wallpaper Rolls" },
      { id: "curtains", label: "Curtains" },
      { id: "blinds", label: "Blinds" },
    ],
  },
  {
    label: "Category",
    name: "category",
    componentType: "select",
    options: [
      { id: "modern", label: "Modern" },
      { id: "classic", label: "Classic" },
      { id: "abstract", label: "Abstract" },
      { id: "geometric", label: "Geometric" },
      { id: "nature", label: "Nature" },
    ],
  },
  {
    label: "Collection",
    name: "collection",
    componentType: "select",
    options: [
      { id: "festive", label: "Festive Collection" },
      { id: "trending", label: "Trending" },
      { id: "minimalist", label: "Minimalist" },
      { id: "luxury", label: "Luxury" },
      { id: "kids", label: "Kids' Collection" },
    ],
  },
  {
    label: "Color",
    name: "color",
    componentType: "input",
    type: "text",
    placeholder: "Enter primary color (e.g., Red, Blue, Beige)",
  },
  {
    label: "Material",
    name: "material",
    componentType: "input",
    type: "text",
    placeholder: "Enter material (e.g., Vinyl, Fabric, Paper)",
  },
  {
    label: "Dimensions",
    name: "dimensions",
    componentType: "input",
    type: "text",
    placeholder: "Enter dimensions (e.g., 10x20 ft)",
  },
  {
    label: "Price",
    name: "price",
    componentType: "input",
    type: "number",
    placeholder: "Enter product price",
  },
  {
    label: "Sale Price",
    name: "salePrice",
    componentType: "input",
    type: "number",
    placeholder: "Enter sale price (optional)",
  },
  {
    label: "Stock Quantity",
    name: "stockQuantity",
    componentType: "input",
    type: "number",
    placeholder: "Enter stock quantity",
  },
  {
    label: "Upload Images",
    name: "images",
    componentType: "file",
    type: "file",
    multiple: true,
    accept: "image/*",
    placeholder: "Upload product images",
  },
];
